# This is a basic workflow that is manually triggered

name: Setup App Installers

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      url:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'URL'
        # Default value if no value is explicitly provided
        default: 'https://XXX.jamfcloud.com'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      clientID:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'API Client ID'
        # Default value if no value is explicitly provided
        default: '13B0FC1F-95B8-47D7-9856-4EA50223200A'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      Secret:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'API Client Secret'
        # Default value if no value is explicitly provided
        default: 'iamtheonewhopoopsintheurinals'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.url }}"
